name: Deploy Ingestion to Dev

on:
  workflow_run:
    workflows: ["Ingestion CI"]
    types: [completed]
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    uses: mbta/workflows/.github/workflows/deploy-ecs.yml@main
    with:
      app-name: lamp-ingestion
      environment: dev
      dockerfile-path: ./py_gtfs_rt_ingestion/
      cluster: lamp
      docker-additional-tags: lamp_ingestion
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      docker-repo: ${{ secrets.INGESTION_DOCKER_URI }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
